<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1578574870226" stop="1578574870226">
  <description>This is the tests collection phase. Failures are modules that failed to collect.</description>
  <name>test_collection_phase</name>
  <title>Collection phase</title>
  <labels/>
  <test-cases>
    <test-case start="1578574870226" status="broken" stop="1578574870226">
      <name>test_piaowu</name>
      <failure>
        <message>failed</message>
        <stack-trace>test_piaowu.py:8: in &lt;module&gt;
    class TestLogin(unittest.TestCase):
test_piaowu.py:21: in TestLogin
    @parameterized.expand(read_excel("test_data.xlsx", "piaowu"))
base\base_excel.py:7: in read_excel
    book = xlrd.open_workbook("..%sdata%s%s" % (os.sep, os.sep, file_name))
F:\python_1\lib\site-packages\xlrd\__init__.py:111: in open_workbook
    with open(filename, "rb") as f:
E   FileNotFoundError: [Errno 2] No such file or directory: '..\\data\\test_data.xlsx'</stack-trace>
      </failure>
      <attachments/>
      <labels/>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
